# Generated by Django 4.1.7 on 2023-09-23 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollw_UnFollw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_follw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follw', to=settings.AUTH_USER_MODEL)),
                ('user_follwing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follwing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
