# Generated by Django 4.2.1 on 2023-09-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_commenttwit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttwit',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to='content.commenttwit'),
        ),
    ]
