# Generated by Django 4.2.1 on 2023-09-23 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='twit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twit_like', to='content.twit'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SaveTwit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('twit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twit_save', to='content.twit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
